[workspace]
members = [
    "contracts/hub",
    "contracts/amp-extractor",
    "contracts/token",
    "contracts/ampz",
    "contracts/amp-compounder/*",
    "contracts/amp-governance/*",
    "packages/*",
    "contracts/arb-vault",
]

[profile.release.package.eris]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
