[package]
name = "eris-staking"
version = "1.0.0"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://www.erisprotocol.com"
repository = "https://github.com/erisprotocol/liquid-staking-contracts"

[dependencies]
cosmwasm-std = "0.16"
cw20 = "0.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
cosmwasm-bignumber = "2.2.0"

[dev-dependencies]
cosmwasm-schema = "0.16.2"