[package]
name = "steak"
version = "1.0.0"
authors = ["larry <gm@larry.engineer>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://steak.club"
repository = "https://github.com/st4k3h0us3/steak-contracts"

[dependencies]
cosmwasm-std = "0.16"
cw20 = "0.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
cosmwasm-bignumber = "2.2.0"
